Repository hzuapps/android-labs-2018, pull requests merged in 2018-04, with the labels that each got.

#554 1614080902234
  soft1614080902234/jietu.jpg
  soft1614080902234/第一次实验报告.md
Labels: Good

#543 #1 #123 第一次实验
  soft1614080902407/Soft1614080902407.PNG
  soft1614080902407/Soft1614080902407Activity.java
  soft1614080902407/report1.md
Labels: Good

#560 #第一次实验报告
  soft1606081301325/jietu/1.PNG
  soft1606081301325/jietu/2.PNG
  soft1606081301325/report1.md
Labels: Good

#559 #1 实验1报告和截图
  Soft1614080902145/p1.PNG
  Soft1614080902145/report1.md
Labels: Good

#557 #1 第一次实验报告
  soft161408090229/#report.md
Labels: Good

#551 #1 #ZZZZmin
  soft1613071002206/Soft1613071002206Activity.java
  soft1613071002206/report.md
  soft1613071002206/soft1613071002206.PNG
Labels: Good

#576 #1 第一次实验 for com
  com1614080901219/com1614080901219.md
  com1614080901219/com1614080901219.png
Labels: Good

#571 #1 第一次实验报告
  soft1614080902227/helloworld.jpg
  soft1614080902227/report.md
Labels: Good

#570 #1 开发环境截图
  soft1614080902236/#report1.md
  soft1614080902236/soft1614080902236.jpg
Labels: Good

#567 第一次实验报告
  soft1614080902135/report.md
  soft1614080902135/实验1..PNG
  soft1614080902135/实验一.jpg
Labels: Good

#577 #1 screen
  com1614080901239/com1614080901239.md
  com1614080901239/com1614080901239.png
Labels: Demo, Good

#580 #1 1614080901138 第一次实验以及实验报告
  com1614080901138/com1614080901138.png
  com1614080901138/report1com1614080901138.md
Labels: Good

#595 "#1 第一次实验"
  com1614080901144/Com1614080901144Activity.PNG
  com1614080901144/No1report.md
Labels: Good

#596 第1次实验报告
  com1614080901244/com1614080901244.jpg
  com1614080901244/report1.md
Labels: Good

#592 #1 第一次实验报告 Com1614080901129
  com1614080901129/Com1614080901129Activity.jpg
  com1614080901129/No.1report.md
Labels: Good

#590 #1 第一次实验截图和报告
  com1614080901131/mmexport1522571608832.jpg
  com1614080901131/report1.md
Labels: Good

#589 #1 第一次实验 (截图版)
  com1614080901238/#report.md
  com1614080901238/Com1614080901238Activity.PNG
Labels: Good

#586 #1 第一次实验报告 for com1614080901134
  com1614080901134/#report1.md
  com1614080901134/com1614080901134.jpg
Labels: Good

#584 我的第一次截图实验
  com1614080901113/1614080901113.png
  com1614080901113/no1report1.md
Labels: Good

#583 #1 #Easadon #第一次实验
  com1614080901110/#1Report.md
  com1614080901110/Com1614080901110.jpg
Labels: Good

#610 #1 实验一截图报告
  soft1614080902314/1代码截图.png
  soft1614080902314/1运行截图.png
  soft1614080902314/report1.md
Labels: Good

#608 #1 第一次截图
  soft1614080902318/Soft1614080902318Activity.png
  soft1614080902318/report1.md
Labels: Good

#607 #1 first report
  Soft1614080902312/#report.md
  Soft1614080902312/Soft1614080902312.png
Labels: Good

#606 #1 the first lab report
  soft1614080902335/Soft1614080902335.png
  soft1614080902335/report1.md
Labels: Good

#605 #1 第一次实验加截图
  soft1614080902427/report1.md
  soft1614080902427/setup.png
Labels: Good

#602 #实验一报告和截图
  soft1614080902315/Soft1614080902315Activity.jpg
  soft1614080902315/实验一报告.md
Labels: Good

#601 第一次实验报告加截图
  Soft1614080902333/开发环境搭建11.png
  Soft1614080902333/第一次实验报告11.md
Labels: Good

#600 #1 搭建运行环境 截图
  soft1614080902302/Soft1614080902302.png
  soft1614080902302/report1.md
Labels: Good

#598 #1 Report_and_Photo
  soft1614080902436/#1report1.md
  soft1614080902436/Soft1614080902436.png
  soft1614080902436/Soft1614080902436Activity.java
Labels: Good

#597 #1 环境搭建报告截图
  com1613090502214/report1.md
  com1613090502214/screen.png
Labels: Good

#591 #1 开发环境的搭建
  com1614080901207/com1614080901207Activity.jpg
  com1614080901207/report1.md
Labels: Good

#626 #1
  soft1614080902102/Soft1614080902102Activity.png
  soft1614080902102/Soft1614080902102Activity1.png
  soft1614080902102/report1.md
Labels: Good

#627 #1first实验报告
  Soft1614080902305/#1first实验报告.md
  Soft1614080902305/Soft1614080902305.jpg
Labels: Good

#624 第一次实验报告截图
  soft1614080902414/report#1.md
  soft1614080902414/运行截图.jpg
Labels: Good

#629 #1 第一次实验（带截图）
  Soft1614080902418/soft1614080902418.PNG
  Soft1614080902418/第一次实验报告.md
Labels: Good

#628 #1 第一次的实验+截图报告
  soft1614080902408/实验报告.md
  soft1614080902408/捕获.PNG
Labels: Good

#623 第一次实验报告+运行截图
  soft1613071002201/report#1.md
  soft1613071002201/运行截图.png
Labels: Good

#619 #1第一次实验截图
  com1614080901103/Com1614080901103report.md
  com1614080901103/com1614080901103.png
Labels: Good

#618 #1 第一次实验截图
  Com1614080901241/GaWa.md
  Com1614080901241/Studio123.png
Labels: Good

#617 #1 实验1报告
  soft1614080902307/report1.md
  soft1614080902307/shiyan1.png
Labels: Good

#615 #1 第一次实验报告加截图
  soft1614080902442/Soft1614080902442Activity.PNG
  soft1614080902442/report1.md
Labels: Good

#613 #1 第一次实验（报告）
  soft1614080902403/pic1.jpg
  soft1614080902403/report1.md
Labels: Good

#616 第一次实验报告和截图
  soft1614080902424/Soft1614080902424Activity.png
  soft1614080902424/report1.md
Labels: Good

#614 #实验一带截图版本
  soft1614080902328/Soft1614080902328.png
  soft1614080902328/实验报告.md
Labels: Good

#612 #1 实验一截图和报告
  soft1614080902416/Soft1614080902416Activity.png
  soft1614080902416/report1.md
Labels: Good

#611 #1 实验一报告与截图
  soft1614080902437/Soft1614080902437.PNG
  soft1614080902437/report1.md
Labels: Good

#637 #1 第一次实验报告
  soft1606081301233/report1.md
  soft1606081301233/shiyanjietu.png
Labels: Good

#636 实验一与截图by msj
  soft1614080902405/#1 report.md
  soft1614080902405/jietu.jpg
  soft1614080902405/soft1614080902405.jpg
Labels: Good

#635 #1 第一次实验报告加截图
  soft1614080902440/Soft1614080902440.png
  soft1614080902440/report1.md
Labels: Good

#632 第一次实验截图，本人做的，但git的默认使用人改不了
  soft1614080902322/#report.md
  soft1614080902322/Soft1614080902322Activity.png
Labels: Good

#656 #1第一次实验报告
  soft1614080902431/report1.md
  soft1614080902431/soft16140809024231.png
Labels: Good

#652 #1 337xhm 第一次实验和运行截图
  soft1614080902337/report1.md
  soft1614080902337/soft1614080902337.png
Labels: Good

#649 I hope I can obtain Good!!
  soft1614080902441/report1.md
  soft1614080902441/soft1614080902441.png
Labels: Good

#648 第一次实验续
  soft1614080902218/1.PNG
  soft1614080902218/report1.md
  soft1614080902218/捕获.PNG
Labels: Good

#647 #1 实验报告+运行截图
  soft1614080902425/soft1614080902425.png
  soft1614080902425/实验报告1.md
Labels: Good

#645 截图和报告015
  Soft1614080902415/002.jpg
  Soft1614080902415/report.md
Labels: Good

#642 #1 first lab part two by zzj
  soft1614080902413/report.md
  soft1614080902413/soft1614080902413.png
Labels: Good

#643 #1 First experiment report
  soft1614080902334/Soft1614080902334Activity.PNG
  soft1614080902334/report1.md
Labels: Good

#639 #1
  soft1614080902445/Soft1614080902445.png
  soft1614080902445/report1.md
Labels: Good

#660 #1 第一次实验报告和截图
  soft1614080902313/report1.md
  soft1614080902313/soft1614080902313Activity.png
Labels: Good

#662 #1 第一次实验报告
  com1614080901101/Com1614080901101Activity.JPG
  com1614080901101/report.md
Labels: Good

#665 #1 第一次实验报告+截图
  com1614080901122/Com1614080901122Activity.jpg
  com1614080901122/report1.md
Labels: Good

#666 #第一次实验报告
  soft1614080902119/picture1.png
  soft1614080902119/picture2.png
  soft1614080902119/report1.md
Labels: Good

#659 第一次实验截图
  soft1614080902344/report1.md
  soft1614080902344/soft1614080902344.png
Labels: Good

#658 .md and image
  com1614080901234/#report.md
  com1614080901234/Com1614080901234.png
Labels: Good

#657 # 第一次实验加截图
  soft1614080902332/001.png
  soft1614080902332/report1.md
Labels: Good

#641 #1 #第一次实验截图及报告
  com1614080901132/#1 #KalorF报告.md
  com1614080901132/com1614080901132.png
Labels: Good

#638 实验截图和实验报告 by lzb
  soft1614080902404/report.md
  soft1614080902404/soft1614080902404.PNG.png
Labels: Good

#677 #1 截图
  com1614080901130/Merged.jpg
  com1614080901130/Screen.jpg
  com1614080901130/report1.md
Labels: Good

#678 #1 截图+实验报告
  soft1613071002123/1613071002123.PNG
  soft1613071002123/report1.md
Labels: Good

#681 first by lgs
  soft1614080902438/report.md
  soft1614080902438/截屏图片.png
Labels: Good

#674 #第一次实验报告+截图
  Com1614080901109/com1614080901109.png
  Com1614080901109/report1.md
Labels: Good

#672 #1 第一次实验报告 for com1614080901133
  com1614080901133/com1614080901133.jpg
  com1614080901133/no1report.md
Labels: Good

#671 # 第一次实验(截图+报告)
  soft1614080902402/Soft1614080902402.png
  soft1614080902402/report1.md
Labels: Good

#689 #1 第一次实验
  com1614080901222/com1614080901222.md
  com1614080901222/com1614080901222.png
Labels: Good

#688 #1 第一次实验
  soft1614080902232/Soft1614080902232Activity.jpg
  soft1614080902232/report1.md
Labels: Good

#687 #1 第一次实验
  soft1614080902205/report1.md
  soft1614080902205/soft1614080902205.png
  soft1614080902205/soft1614080902205实验1（1）.png
  soft1614080902205/soft1614080902205实验1（2）.png
Labels: Good

#686 #第1次实验报告
  soft1614080902204/report1.md
  soft1614080902204/shiyanjieguo.png
  soft1614080902204/shiyanjietu.png
Labels: Good

#668 #1 first lab 309
  soft1614080902309/soft1614080902309.md
  soft1614080902309/soft1614080902309.png
Labels: Good

#682 #1 第一次实验与截图
  Soft1614080902432/report.md
  Soft1614080902432/实验截图.png
Labels: Good

#683 #1 第一次试验报告
  soft1614080902117/report1.md
  soft1614080902117/shiyan1.PNG
  soft1614080902117/shiyan2.PNG
Labels: Good

#684 #第一次实验报告及截图（修改）
  soft1614080902138/11.png
  soft1614080902138/report1.md
  soft1614080902138/捕获.PNG
Labels: Good

#699 #1 实验1报告+截图
  soft1614080902211/02.PNG
  soft1614080902211/report1.md
Labels: Good

#700 #1 第一次实验截图+实验报告
  soft1614080902417/Soft1614080902417.png
  soft1614080902417/report 1.md
Labels: Good

#952 第二次实验
  soft1614080902234/AndroidManifest.xml
  soft1614080902234/activity_soft1614080902234_main.xml
  soft1614080902234/soft1614080902234MainActivity.java
  soft1614080902234/strings.xml
  soft1614080902234/第二次实验报告.md
Labels: Good

#953 #2 #903 第二次实验模拟迅雷下载功能
  soft1614080902217/AndroidManifest.xml
  soft1614080902217/Soft1614080902217Activity.java
  soft1614080902217/activity_soft1614080902217.xml
  soft1614080902217/strings.xml
Labels: Good

#965 #第二次实验新浪微博小功能
  soft1614080902115/app/java/myapplication/Soft1614080902115MainActivity.java
  soft1614080902115/app/manifests/AndroidManifest.xml
  soft1614080902115/app/res/layout/activity_soft1614080902115_main.xml
  soft1614080902115/app/res/values/strings.xml
  soft1614080902115/report2.md
Labels: Good

#956 #2 #881 第2次实验
  soft1614080902117/MyApplication8/app/src/main/AndroidManifest.xml
  soft1614080902117/MyApplication8/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902117/myapplication/Soft1614080902117Activity.java
  soft1614080902117/MyApplication8/app/src/main/res/layout/activity_soft1614080902117.xml
  soft1614080902117/MyApplication8/app/src/main/res/values/strings.xml
  soft1614080902117/Soft1614080902117Activity.java
  soft1614080902117/report2.md
Labels: Good

#955 #2 #885 第二次实验
  soft1614080902119/Soft1614080902119Activity.java
  soft1614080902119/app/src/main/AndroidManifest.xml
  soft1614080902119/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902119activity/soft1614080902119/soft1614080902119MainActivity.java
  soft1614080902119/app/src/main/res/layout/activity_soft1614080902119_main.xml
  soft1614080902119/app/src/main/res/values/strings.xml
  soft1614080902119/report2.md
Labels: Good

#1054 #2 #1039 加法计算器
  soft1614080902416/java/edu.hzuapps.androidlabs.soft1614080902416/soft1614080902416Activity.java
  soft1614080902416/manifests/AndroidManifest.xml
  soft1614080902416/report2.md
  soft1614080902416/res/layout/activity_soft1614080902416.xml
  soft1614080902416/res/values/strings.xml
Labels: Good

#1056 #2 #880 第二次实验
  Soft1614080902137/app/src/main/AndroidManifest.xml
  Soft1614080902137/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902137/Soft1614080902137Activity.java
  Soft1614080902137/app/src/main/res/layout/activity_soft1614080902137.xml
  Soft1614080902137/app/src/main/res/values/strings.xml
  Soft1614080902137/第二次实验报告.md
Labels: Good

#1045 #3 #1024 皮皮钟
  soft1614080902413/java/edu/hzuapps/androidlabs/soft1614080902413/soft1614080902413Activity.java
  soft1614080902413/manifests/AndroidManifest.xml
  soft1614080902413/report1.md
  soft1614080902413/report2.md
  soft1614080902413/res/layout/activity_soft1614080902413.xml
  soft1614080902413/res/values/strings.xml
Labels: Good

#1043 #2 #887 第二次实验
  soft1614080902125/Soft1614080902125Activity.java
  soft1614080902125/app/src/main/AndroidManifest.xml
  soft1614080902125/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902125/Soft1614080902125Activity.java
  soft1614080902125/app/src/main/res/layout/activity_soft1614080902125.xml
  soft1614080902125/app/src/main/res/values/strings.xml
  soft1614080902125/report2.md
Labels: Good

#1042 第二次实验
  Soft1614080902415/java/Soft1614080902415MainActivity.java
  Soft1614080902415/layout/activity_soft1614080902415_main.xml
  Soft1614080902415/manifests/AndroidManifest.xml
  Soft1614080902415/report2.md
  Soft1614080902415/values/strings.xml
Labels: Good

#1070 #2 #976 第二次实验
  soft1614080902334/AndroidManifest.xml
  soft1614080902334/java/edu/hzuapps/androidlabs/soft1614080902334/Soft1614080902334WeatherActivity.java
  soft1614080902334/report2.md
  soft1614080902334/res/layout/activity_soft1614080902334_weather.xml
  soft1614080902334/res/values/strings.xml
Labels: Good

#1062 #2 #1020 第二次实验 睡眠大师
  soft1614080902442/java/soft1614080902442Activity.java
  soft1614080902442/mainifests/AndroidManifest.xml
  soft1614080902442/report2.md
  soft1614080902442/res/layout/activity_soft1614080902442.xml
  soft1614080902442/res/values/colors.xml
  soft1614080902442/res/values/strings.xml
  soft1614080902442/res/values/styles.xml
  soft1614080902442/第二次实验截图.png
Labels: Good

#1060 #2 #970 事件提醒
  soft1614080902313/java/eventreminder/Soft1614080902313EventReminderActivity.java
  soft1614080902313/manifests/AndroidManifest.xml
  soft1614080902313/report2.md
  soft1614080902313/res/layout/activity_soft1614080902313_event_reminder.xml
  soft1614080902313/res/values/strings.xml
Labels: Good

#1078 #2 #999 第二次实验-绿色音乐播放器
  soft1614080902427/java/edu.hzuapps.androidlabs.soft1614080902427/Soft1614080902427Activity.java
  soft1614080902427/manifests/AndroidManifest.xml
  soft1614080902427/report2.md
  soft1614080902427/res/layout/activity_soft1614080902427.xml
  soft1614080902427/res/values/strings.xml
  soft1614080902427/simulator.jpg
Labels: Good

#1080 #2#1032 第二次实验带截图
  Soft1614080902422/#2.png
  Soft1614080902422/#2report2.md
  Soft1614080902422/java/edu/hzuapps/androidlabs/soft1614080902422/Soft1614080902422Activity.java
  Soft1614080902422/manifests/AndroidManifest.xml
  Soft1614080902422/res/layout/activity_soft1614080902422.xml
  Soft1614080902422/res/values/strings.xml
Labels: Good

#1095 #2 #938 万能遥控器
  soft1614080902227/app/src/main/AndroidManifest.xml
  soft1614080902227/app/src/main/java/com/example/soft1614080902227activity/Soft1614080902227Activity.java
  soft1614080902227/app/src/main/res/layout/activity_soft1614080902227.xml
  soft1614080902227/app/src/main/res/values/strings.xml
Labels: Good

#1098 #1001 第二次实验
  soft1614080902417/My Report2.md
  soft1614080902417/java/Soft1614080902417Activity.java
  soft1614080902417/layout/activity_soft1614080902417.xml
  soft1614080902417/layout/content_soft1614080902417.xml
  soft1614080902417/report 1.md
  soft1614080902417/values/strings.xml
Labels: Good

#1106 第一次实验报告+截图（多了个文件，已删除）
  soft1614080902106/1report.md
Labels: Late

#1119 #2 #940 通讯录
  soft1614080902110/1report.md
  soft1614080902110/2.png
  soft1614080902110/Soft1614080902110.java
  soft1614080902110/app/src/main/AndroidManifest.xml
  soft1614080902110/app/src/main/java/androidlabs/hzuapps/edu/soft1614080902110/Soft1614080902110Activity.java
  soft1614080902110/app/src/main/res/layout/activity_soft1614080902110.xml
  soft1614080902110/app/src/main/res/values/strings.xml
  soft1614080902110/report1.md
  soft1614080902110/report2.md
Labels: Good

#1109 #1 第一次实验+报告
  soft1614080902230/report.md
  soft1614080902230/soft1614080902230.png
Labels: Late

#1130 #1#第一次实验报告和截图
  Soft1614080902144/report1.md
  Soft1614080902144/soft1614080902144.png
Labels: Late

#1132 #2 #957 第二次实验
  soft1614080902221/app/src/main/AndroidManifest.xml
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Soft1614080902221Activity.java
  soft1614080902221/app/src/main/res/layout/activity_soft1614080902221.xml
  soft1614080902221/app/src/main/res/values/strings.xml
  soft1614080902221/report2.md
Labels: Good

#1137 #2 231第二次实验
  soft1614080902231/app/src/main/AndroidManifest.xml
  soft1614080902231/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902231/Soft1614080902231Activity.java
  soft1614080902231/app/src/main/res/layout/activity_soft1614080902231.xml
  soft1614080902231/app/src/main/res/values/strings.xml
  soft1614080902231/report2.md
Labels: Good

#1125 #2 #1004 第二次实验
  soft1614080902318/#2 #1004 report.md
  soft1614080902318/AndroidManifest.xml
  soft1614080902318/java/edu/hzuapps/androidlabs/soft1614080902318/Soft1614080902318Activity.java
  soft1614080902318/res/values/strings.xml
Labels: Good

#1123 #1 第一次试验修改
  com1614080901102/788%2D51G)QQFL_U%1$KJPN.png
  com1614080901102/Com1614080901102Activity.java
  com1614080901102/report1.md
Labels: Late

#1145 #2 #1030 天气查询
  soft1614080902310/java/soft1614080902310/androidlabs/hzuapps/edu/weather_report/Soft1614080902310weather_reportActivity.java
  soft1614080902310/manifests/AndroidManifest.xml
  soft1614080902310/report2.md
  soft1614080902310/res/layout/activity_soft1614080902310weather_report.xml
  soft1614080902310/res/values/strings.xml
Labels: Good

#1146 #2 #1006 小说阅读器实验二
  soft1614080902328/app/src/main/AndroidManifest.xml
  soft1614080902328/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902328/Soft1614080902328Activity1.java
  soft1614080902328/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902328/Soft1614080902328Activity2.java
  soft1614080902328/app/src/main/res/layout/soft_1614080902328_activity1.xml
  soft1614080902328/app/src/main/res/layout/soft_1614080902328_activity2.xml
  soft1614080902328/app/src/main/res/values/strings.xml
  soft1614080902328/实验2报告.md
Labels: Good

#1147 #2 #913 简单的资源管理器
  soft1606081301325/report2.md
  soft1606081301325/实验2/AndroidManifest.xml
  soft1606081301325/实验2/Soft1606081301325Activity.java
  soft1606081301325/实验2/activity_soft1606081301325.xml
  soft1606081301325/实验2/strings.xml
Labels: Good

#1148 #2#920保留文件夹的原始结构
  soft1606081301233/app/src/main/AndroidManifest.xml
  soft1606081301233/app/src/main/java/edu/hzuapps/androidlabs/soft1606081301233/Soft1606081301233Activity.java
  soft1606081301233/app/src/main/res/layout/activity_soft1606081301233.xml
  soft1606081301233/app/src/main/res/values/strings.xml
  soft1606081301233/report2.md
Labels: Good

#1153 #1#第1次实验截图
  soft1614080902126/report1.md
  soft1614080902126/截图1.png
  soft1614080902126/截图2.png
Labels: Late

#1144 #2 第二次实验 类似懂球帝
  soft1614080902315/app/src/main/AndroidManifest.xml
  soft1614080902315/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902315/Soft1614080902315Activity.java
  soft1614080902315/app/src/main/res/layout/soft_1614080902315_activity.xml
  soft1614080902315/app/src/main/res/values/strings.xml
  soft1614080902315/实验二报告.md
Labels: Good

#1143 #2 #11 实验2（程序名：TIM）增加文件夹结构
  Soft1614080902145/#2实验结果截图.png
  Soft1614080902145/TIM/src/main/java/com/example/hao/soft1614080902145/MainActivity.java
  Soft1614080902145/TIM/src/main/res/AndroidManifest.xml
  Soft1614080902145/TIM/src/main/res/layout/activity_main.xml
  Soft1614080902145/TIM/src/main/res/values/strings.xml
  Soft1614080902145/report2.md
Labels: Good

#1141 #2 #1013 失物招领第二次实验
  soft1614080902332/app/src/main/AndroidManifest.xml
  soft1614080902332/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902332/Soft1614080902332Activity1.java
  soft1614080902332/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902332/Soft1614080902332Activity2.java
  soft1614080902332/app/src/main/res/layout/soft_1614080902332_activity1.xml
  soft1614080902332/app/src/main/res/layout/soft_1614080902332_activity2.xml
  soft1614080902332/app/src/main/res/values/strings.xml
  soft1614080902332/report2.md
Labels: Good

#1159 #2 第二次实验记事本
  soft1614080902409/2.png
  soft1614080902409/app/java/soft1614080902409activity.java
  soft1614080902409/app/manifests/AndroidManifest.xml
  soft1614080902409/app/res/layout/activity_soft1614080902409.xml
  soft1614080902409/app/res/values/strings.xml
  soft1614080902409/report1.md
  soft1614080902409/report2.md
  soft1614080902409/soft1614080902409.png
Labels: Good

#1160 第二次实验+截图，快递下单
  soft1614080902424/app/java/edu.hzuapps.androidlabs.Soft1614080902424/Soft1614080902424Activity.java
  soft1614080902424/app/manifests/AndroidManifest.xml
  soft1614080902424/app/res/layout/soft_1614080902424_activity.xml
  soft1614080902424/app/res/values/strings.xml
  soft1614080902424/report2.md
  soft1614080902424/实验2.png
Labels: Good

#1162 第1次实验报告
  soft1614080902214/jietu.png
  soft1614080902214/report1.md
  soft1614080902214/soft1614080902214Activity.java
Labels: Late

#1164 #2 #1161 词汇测试
  soft1614080902319/report2.md
  soft1614080902319/实验2/AndroidManifest.xml
  soft1614080902319/实验2/java/edu/hzuapps/androidlabs/Soft1614080902319Activity/MainActivity.java
  soft1614080902319/实验2/res/layout/activity_main.xml
  soft1614080902319/实验2/res/values/strings.xml
Labels: Good

#1157 #2 #995 空课室申请第二次实验
  soft1614080902309/app/src/main/AndroidManifest.xml
  soft1614080902309/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902309/Soft1614080902309Activity.java
  soft1614080902309/app/src/main/res/layout/soft_1614080902309_activity.xml
  soft1614080902309/app/src/main/res/values/strings.xml
  soft1614080902309/report2.md
Labels: Good

#1183 #2第二次实验-微信
  soft1614080902405/main/AndroidManifest.xml
  soft1614080902405/main/java/soft1614080902405.java
  soft1614080902405/main/report2.md
  soft1614080902405/main/res/layout/activity_soft1614080902405.xml
  soft1614080902405/main/res/values/strings.xml
  soft1614080902405/main/shiyaner.jpg
Labels: Good

#1170 #1 #433第一次实验
  soft1614080902433/Soft1614080902433Activity.java
Labels: Late

#1171 #2#888 第二次实验-学生宿舍入住管理系统
  soft1614080902102/app/src/main/AndroidManifest.xml
  soft1614080902102/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902102/soft1614080902102MainActivity.java
  soft1614080902102/app/src/main/res/layout/activity_soft1614080902102_main.xml
  soft1614080902102/app/src/main/res/values/strings.xml
  soft1614080902102/report2.md
Labels: Good

#1177 #2 #1059 第二次实验录音机
  soft1614080902104/Soft1614080902104第二次实验截图.png
  soft1614080902104/app/src/main/AndroidManifest.xml
  soft1614080902104/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902104/soft1614080902104Activity.java
  soft1614080902104/app/src/main/res/layout/activity_soft1614080902104.xml
  soft1614080902104/app/src/main/res/values/strings.xml
  soft1614080902104/report2.md
Labels: Good

#1202 第一次实验
  soft1614080902202/report md
  soft1614080902202/soft1614080902202.java
Labels: Late

#1251 report.1
  soft1614080902242/QQ截图20180415095812.png
  soft1614080902242/report1.md
Labels: Late

#1260 第一次实验修改后及报告
  Soft1614080902105/report.md
  Soft1614080902105/soft1614080902105activity.java
  Soft1614080902105/第一次实验报告截图.png
Labels: Late

#1296 #1 第一次实验
  soft1614080902224/123.jpg
  soft1614080902224/report.md
  soft1614080902224/soft1614080902224Activity.java
Labels: Late

#1313 #1 第一次实验+截图
  soft1614080902141/report1.md
  soft1614080902141/sort1614080902141.PNG
Labels: Late

#1354 #3 #890 第三次实验
  soft1614080902233/app/src/main/AndroidManifest.xml
  soft1614080902233/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902233/SecordActivity.java
  soft1614080902233/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902233/Soft1614080902233Activity.java
  soft1614080902233/app/src/main/res/drawable/maomao.jpg
  soft1614080902233/app/src/main/res/layout/activity_secord.xml
  soft1614080902233/app/src/main/res/layout/activity_soft1614080902233.xml
  soft1614080902233/app/src/main/res/values/strings.xml
  soft1614080902233/repert3.md
  soft1614080902233/ropert2.md
  soft1614080902233/tupian3.1.png
  soft1614080902233/tupian3.2.png
Labels: Good

#1437 #1001 第三次实验
  soft1614080902417/#3/336117211670429537.jpg
  soft1614080902417/#3/395277057291056000.jpg
  soft1614080902417/#3/My Report 3.md
  soft1614080902417/#3/drawable/i_o.png
  soft1614080902417/#3/drawable/ic_launcher_background.xml
  soft1614080902417/#3/drawable/mau5trap2.png
  soft1614080902417/#3/java/NewActivity.java
  soft1614080902417/#3/java/Soft1614080902417Activity.java
  soft1614080902417/#3/layout/activity_new.xml
  soft1614080902417/#3/layout/activity_soft1614080902417.xml
  soft1614080902417/#3/layout/content_new.xml
  soft1614080902417/#3/layout/content_soft1614080902417.xml
  soft1614080902417/#3/values/strings.xml
Labels: Cheat

#1435 #3 #1015 实验三+截图
  soft1614080902407/java/edu/hzuapps/androidlabs/soft1614080902407/SecondActivity.java
  soft1614080902407/java/edu/hzuapps/androidlabs/soft1614080902407/Soft1614080902407Activity_1.java
  soft1614080902407/report3.md
  soft1614080902407/res/drawable/background.jpg
  soft1614080902407/res/drawable/ic_launcher_background.xml
  soft1614080902407/res/layout/activity_second.xml
  soft1614080902407/res/layout/activity_soft1614080902407_1.xml
  soft1614080902407/res/values/colors.xml
  soft1614080902407/res/values/strings.xml
  soft1614080902407/res/values/styles.xml
  soft1614080902407/实验3截图1.jpg
  soft1614080902407/实验3截图2.jpg
Labels: Good

#1371 #1 第一次实验报告加截图
  com1614080901136/Com1614080901136Activity.java
  com1614080901136/com1614080901136.jpg
  com1614080901136/report1.md
Labels: Late

#1382 #3 #918
  soft1614080902112/AndroidManifest.xml
  soft1614080902112/SecondActivity.JPG
  soft1614080902112/Soft1614080902112Activity.JPG
  soft1614080902112/java/com/example/a14775/soft1614080902112activity/SecondActivity.java
  soft1614080902112/java/com/example/a14775/soft1614080902112activity/Soft1614080902112Activity.java
  soft1614080902112/report3
  soft1614080902112/res/drawable/bj.jpg
  soft1614080902112/res/drawable/tubiao2.jpg
  soft1614080902112/res/drawable/tubiao3.jpg
  soft1614080902112/res/drawable/tubiao_1.jpg
  soft1614080902112/res/layout/activity_second.xml
  soft1614080902112/res/layout/activity_soft1614080902112.xml
  soft1614080902112/res/values-w820dp/dimens.xml
  soft1614080902112/res/values/colors.xml
  soft1614080902112/res/values/dimens.xml
  soft1614080902112/res/values/strings.xml
  soft1614080902112/res/values/styles.xml
Labels: Good

#1400 #3 #957 第三次实验截图加报告
  soft1614080902221/app/src/main/AndroidManifest.xml
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Activity2.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Soft1614080902221Activity.java
  soft1614080902221/app/src/main/res/drawable/ic_launcher_background.xml
  soft1614080902221/app/src/main/res/drawable/picture1.png
  soft1614080902221/app/src/main/res/drawable/picture2.png
  soft1614080902221/app/src/main/res/layout/activity_2.xml
  soft1614080902221/app/src/main/res/layout/activity_soft1614080902221.xml
  soft1614080902221/app/src/main/res/values/colors.xml
  soft1614080902221/app/src/main/res/values/dimens.xml
  soft1614080902221/app/src/main/res/values/strings.xml
  soft1614080902221/app/src/main/res/values/styles.xml
  soft1614080902221/report3.md
  soft1614080902221/第三次实验运行截图1.png
  soft1614080902221/第三次实验运行截图2.png
Labels: Good

#1408 #1 实验一（截图）
  soft1614080902439/report1.md
  soft1614080902439/soft1614080902439.java
  soft1614080902439/soft1614080902439.png
Labels: Late
