Repository hzuapps/android-labs-2018, pull requests merged in 2018-05, with the labels that each got.

#1496 #3 #991 第三次实验修改版
  soft1614080902440/Third/report3.md
  soft1614080902440/Third/res/colors.xml
  soft1614080902440/Third/res/ic_launcher_background.xml
  soft1614080902440/Third/res/ic_launcher_foreground.xml
  soft1614080902440/Third/res/styles.xml
  soft1614080902440/Third/third.md
Labels: Demo

#1505 #3 实验三守望先锋掌游宝
  soft1614080902408/app/java/edu.hzuapps.androidlabs.soft1614080902408/Soft1614080902408_LoginActivity.java
  soft1614080902408/app/java/edu.hzuapps.androidlabs.soft1614080902408/Soft1614080902408_zhangyoubao.java
  soft1614080902408/app/res/drawable/ow.jpg
  soft1614080902408/app/res/drawable/owlogo.jpg
  soft1614080902408/app/res/layout/activity_soft1614080902408__login.xml
  soft1614080902408/app/res/layout/activity_soft1614080902408_zhangyoubao.xml
  soft1614080902408/report3.md
  soft1614080902408/实验三.1.png
  soft1614080902408/实验三.2.png
Labels: Demo

#1695 #1 第一次实验
  soft1614080902336/Soft1614080902336Activity.java
Labels: Late

#1700 #1 第一次实验 for com
  com1614080901127/Com1614080901127Activity.java
Labels: Late

#1702 #4 第四次实验
  com1613090502214/project/app/src/main/java/edu/hzuapps/androidlabs/com1613090502214/SecondActivity.java
  com1613090502214/project/app/src/main/res/layout/activity_com1613090502214.xml
  com1613090502214/project/app/src/main/res/layout/activity_second.xml
  com1613090502214/project/app/src/main/res/values/arrays.xml
  com1613090502214/report4.md
  com1613090502214/ui1.png
  com1613090502214/ui2.png
Labels: Good

#1722 #4 #999 第4次实验
  soft1614080902427/Screenshot_1525757754.png
  soft1614080902427/java/edu/hzuapps/androidlabs/soft1614080902427/Player.java
  soft1614080902427/java/edu/hzuapps/androidlabs/soft1614080902427/Soft1614080902427Activity.java
  soft1614080902427/layout.png
  soft1614080902427/manifests/AndroidManifest.xml
  soft1614080902427/report4.md
  soft1614080902427/res/drawable/bg.jpg
  soft1614080902427/res/drawable/media_next.png
  soft1614080902427/res/drawable/media_pause.png
  soft1614080902427/res/drawable/media_play.png
  soft1614080902427/res/drawable/roundedbutton.xml
  soft1614080902427/res/drawable/song_list_item_selected_background.xml
  soft1614080902427/res/drawable/star_empty.png
  soft1614080902427/res/drawable/star_full.png
  soft1614080902427/res/layout/activity_player.xml
  soft1614080902427/res/layout/song_list_item.xml
  soft1614080902427/res/values/colors.xml
Labels: Good

#1719 #4 第四次实验
  soft1614080902318/#3/java/edu/hzuapps/androidlabs/soft1614080902318/startActivity.java
  soft1614080902318/#3/res/drawable/ali.jpg
  soft1614080902318/#3/res/drawable/taozi.jpg
  soft1614080902318/#3/res/layout/activity_start.xml
  soft1614080902318/pk1.png
  soft1614080902318/pk2.png
  soft1614080902318/pk3.png
  soft1614080902318/pkmain.png
  soft1614080902318/report/report1.md
  soft1614080902318/report/report2.md
  soft1614080902318/report/report3.md
  soft1614080902318/report/report4.md
Labels: Good

#1730 #4 第四次实验+报告
  com1614080901118/Com1614080901118/app/src/main/java/edu/hzuapps/androidlabs/com1614080901118/SecondActivity.java
  com1614080901118/Com1614080901118/app/src/main/res/drawable-v24/iv_eyu.png
  com1614080901118/Com1614080901118/app/src/main/res/drawable-v24/iv_huangzi.png
  com1614080901118/Com1614080901118/app/src/main/res/drawable-v24/iv_nuoshou.png
  com1614080901118/Com1614080901118/app/src/main/res/drawable-v24/iv_ruiwen.png
  com1614080901118/Com1614080901118/app/src/main/res/drawable-v24/iv_timo.png
  com1614080901118/Com1614080901118/app/src/main/res/drawable-v24/iv_yasuo.png
  com1614080901118/Com1614080901118/app/src/main/res/layout/activity_com1614080901118.xml
  com1614080901118/Com1614080901118/app/src/main/res/layout/activity_second.xml
  com1614080901118/Com1614080901118/app/src/main/res/values/strings.xml
  com1614080901118/report4.md
Labels: Good

#1760 #4 #976 第四次实验
  soft1614080902334/java/edu/hzuapps/androidlabs/soft1614080902334/BasicActivity.java
  soft1614080902334/java/edu/hzuapps/androidlabs/soft1614080902334/CityInfoActivity.java
  soft1614080902334/java/edu/hzuapps/androidlabs/soft1614080902334/Soft1614080902334WeatherActivity.java
  soft1614080902334/lab4_screenshot_1.png
  soft1614080902334/lab4_screenshot_2.png
  soft1614080902334/lab4_screenshot_3.png
  soft1614080902334/report4.md
  soft1614080902334/res/drawable/ic_launcher_background.xml
  soft1614080902334/res/drawable/minibar.xml
  soft1614080902334/res/layout/activity_basic.xml
  soft1614080902334/res/layout/activity_cityinfo.xml
Labels: Good

#1827 #4 第四次实验
  soft1614080902431/MyFirstApplication/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902431/InterfaceActivity.java
  soft1614080902431/MyFirstApplication/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902431/Main2Activity.java
  soft1614080902431/MyFirstApplication/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902431/SendActivity.java
  soft1614080902431/MyFirstApplication/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902431/Soft1614080902431Activity.java
  soft1614080902431/MyFirstApplication/app/src/main/res/layout/activity_interface.xml
  soft1614080902431/MyFirstApplication/app/src/main/res/layout/activity_main2.xml
  soft1614080902431/MyFirstApplication/app/src/main/res/layout/activity_send.xml
  soft1614080902431/MyFirstApplication/app/src/main/res/layout/activity_soft1614080902431.xml
  soft1614080902431/report4.md
  soft1614080902431/应用图标界面soft1614080902431Activity.png
  soft1614080902431/查看信息界面Main2Activity.png
  soft1614080902431/菜单选择界面InterfaceActivity.png
  soft1614080902431/输入信息后截图SendActivity.png
  soft1614080902431/输入信息界面SendActivity.png
Labels: Good

#1851 第二次实验
  soft1614080902209/app/src/main/AndroidManifest.xml
  soft1614080902209/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902209/Soft1614080902209.java
  soft1614080902209/app/src/main/res/layout/menu_soft1614080902209.xml
  soft1614080902209/app/src/main/res/values/strings.xml
  soft1614080902209/report2.md
Labels: Late

#1952 #5 #1370实验五
  com1613090502214/#5Screenshot.png
  com1613090502214/#5data.png
  com1613090502214/project/app/src/main/java/edu/hzuapps/androidlabs/com1613090502214/SecondActivity.java
  com1613090502214/report5.md
Labels: Good

#2011 #2 第二次实验+实验报告
  com1614080901127/app/main/AndroidManifest.xml
  com1614080901127/app/main/java/edu/hzuapps/androidlabs/com1614080901127/Com1614080901127Activity.java
  com1614080901127/app/main/res/layout/activity_com1614080901127.xml
  com1614080901127/app/main/res/values/strings.xml
  com1614080901127/report.md
Labels: Late

#1943 Soft337 实验四
  soft1614080902337/app/java/Soft1614080902337Activity2.java
  soft1614080902337/app/mainfests/AndroidManifest.xml
  soft1614080902337/app/res/layout/activity_soft1614080902337.xml
  soft1614080902337/app/res/layout/activity_soft16140809023372.xml
  soft1614080902337/report4.md
  soft1614080902337/report5.md
  soft1614080902337/实验4截图/实验四1.png
  soft1614080902337/实验4截图/实验四2.png
  soft1614080902337/实验4截图/实验四3.png
  soft1614080902337/实验5截图/实验五1.png
  soft1614080902337/实验5截图/实验五2.png
Labels: Good

#1957 #3 #1595第三次实验
  com1614080901123/3-1.png
  com1614080901123/3-2.png
  com1614080901123/app/src/main/AndroidManifest.xml
  com1614080901123/app/src/main/java/com/example/hzu/com1614080901123/com1614080901123Activity.java
  com1614080901123/app/src/main/java/com/example/hzu/com1614080901123/secondActivity.java
  com1614080901123/app/src/main/res/drawable/tu1.png
  com1614080901123/app/src/main/res/drawable/tu2.png
  com1614080901123/app/src/main/res/layout/Com1614080901123activity.xml
  com1614080901123/app/src/main/res/layout/activity_com1614080901123.xml
  com1614080901123/app/src/main/res/layout/activity_second.xml
  com1614080901123/app/src/main/res/values/strings.xml
  com1614080901123/app/src/main/res/values/styles.xml
Labels: Late

#1972 #3 #1609 第三次实验
  com1614080901143/app/src/main/AndroidManifest.xml
  com1614080901143/app/src/main/java/edu/hzuapps/androidlabs/com1614080901143/com1614080901143Activity.java
  com1614080901143/app/src/main/java/edu/hzuapps/androidlabs/com1614080901143/com_1614080901143Activity.java
  com1614080901143/app/src/main/res/drawable-v24/cgz.jpg
  com1614080901143/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  com1614080901143/app/src/main/res/layout/activity_com1614080901143.xml
  com1614080901143/app/src/main/res/layout/activity_com_1614080901143.xml
  com1614080901143/report3.md
  com1614080901143/截图1.jpg
  com1614080901143/截图2.jpg
Labels: Late

#1983 第二次实验
  Com1614080901228/app/src/main/AndroidManifest.xml
  Com1614080901228/app/src/main/java/com1614080901228/androidlabs/hzuapps/edu/com1614080901228/Com1614080901228Activity.java
  Com1614080901228/app/src/main/res/layout/activity_com1614080901228.xml
  Com1614080901228/app/src/main/res/values/strings.xml
  Com1614080901228/report2.md
Labels: Late

#1991 #5 #999 第五次实验
  soft1614080902427/Screenshot_1526454044.png
  soft1614080902427/Screenshot_1526454716.png
  soft1614080902427/Screenshot_1526454721.png
  soft1614080902427/java/edu/hzuapps/androidlabs/soft1614080902427/Player.java
  soft1614080902427/report5.md
  soft1614080902427/res/menu/simple_menu.xml
  soft1614080902427/res/values/strings.xml
Labels: Good

#2002 #5 #957 第五次实验
  soft1614080902221/app/src/main/AndroidManifest.xml
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Activity2.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Activity3.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Activity4.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/MydatabaseHelper.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/PlayerData.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/PlayerDataAdapter.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Soft1614080902221Activity.java
  soft1614080902221/app/src/main/res/layout/activity_3.xml
  soft1614080902221/app/src/main/res/layout/activity_4.xml
  soft1614080902221/app/src/main/res/layout/playerdata_item.xml
  soft1614080902221/report5.md
  soft1614080902221/第5次实验截图1.gif
  soft1614080902221/第5次实验截图2.gif
Labels: Good

#2003 #5 #1004 第五次实验
  soft1614080902318/#3/java/edu/hzuapps/androidlabs/soft1614080902318/startActivity.java
  soft1614080902318/report/report5.md
  soft1614080902318/result.png
Labels: Cheat

#1995 #5 实验五
  Soft1614080902317/#5_1.PNG
  Soft1614080902317/#5_2.PNG
  Soft1614080902317/java/soft1614080902317/androidlabs/hzuapps/edu/tripmanager/ModifyTrip.java
  Soft1614080902317/report5.md
  Soft1614080902317/res/layout/activity_modify_trip.xml
Labels: Cheat

#2013 #3 第三次实验
  Soft1614080902140/app/src/main/AndroidManifest.xml
  Soft1614080902140/app/src/main/java/Soft1614080902140CoverActivity.java
  Soft1614080902140/app/src/main/java/Soft1614080902140HomeActivity.java
  Soft1614080902140/app/src/main/res/drawable/timg.jpg
  Soft1614080902140/app/src/main/res/layout/activity_soft1614080902140_cover.xml
  Soft1614080902140/app/src/main/res/layout/activity_soft1614080902140_home.xml
  Soft1614080902140/app/src/main/res/values/strings.xml
  Soft1614080902140/cover.png
  Soft1614080902140/home.png
  Soft1614080902140/report3.md
Labels: Late

#2015 #5 #1344 第五次实验
  com1614080901134/5.png
  com1614080901134/6.png
  com1614080901134/app/src/main/java/edu/hzuapps/androidlabs/com1614080901134/com16140809011342Activity.java
  com1614080901134/datawenjian.png
  com1614080901134/report5.md
Labels: Good

#2008 第五次实验
  soft1614080902227/app/src/main/AndroidManifest.xml
  soft1614080902227/app/src/main/java/com/example/soft1614080902227activity/Remote_0f_Air.java
  soft1614080902227/app/src/main/java/com/example/soft1614080902227activity/Soft1614080902227Activity.java
  soft1614080902227/app/src/main/java/com/example/soft1614080902227activity/UserDBHelper.java
  soft1614080902227/app/src/main/res/drawable/button.xml
  soft1614080902227/app/src/main/res/drawable/chushi.png
  soft1614080902227/app/src/main/res/drawable/tongfeng.png
  soft1614080902227/app/src/main/res/drawable/zhileng.png
  soft1614080902227/app/src/main/res/drawable/zhire.png
  soft1614080902227/app/src/main/res/drawable/zidong.png
  soft1614080902227/app/src/main/res/layout/activity_remote_0f__air.xml
  soft1614080902227/app/src/main/res/layout/activity_soft1614080902227.xml
  soft1614080902227/app/src/main/res/layout/activity_user_dbhelper.xml
  soft1614080902227/app/src/main/res/values/colors.xml
  soft1614080902227/app/src/main/res/values/dimens.xml
  soft1614080902227/report5.md
  soft1614080902227/第五次实验截图.jpg
Labels: Good

#2021 #5 实验五 数据存储
  soft1614080902414/main4/6181F5410E0639CB3A6168EAC66D5535.jpg
  soft1614080902414/main4/java/com/example/chx/soft1614080902414/Soft1614080902414Activity.java
  soft1614080902414/main4/repoter5.md
  soft1614080902414/main4/res/layout/activity_soft1614080902414.xml
Labels: Good

#2023 #3 第3次实验
  com1614080901136/app/src/main/AndroidManifest.xml
  com1614080901136/app/src/main/java/com1614080901136/androidlabs/hzuapps/edu/com1614080901136/MainActivity.java
  com1614080901136/app/src/main/java/com1614080901136/androidlabs/hzuapps/edu/com1614080901136/SecordActivity.java
  com1614080901136/app/src/main/res/drawable/YY.jpg
  com1614080901136/app/src/main/res/layout/activity_main.xml
  com1614080901136/app/src/main/res/values/strings.xml
  com1614080901136/pic.png
  com1614080901136/report3.md
Labels: Late

#2024 #5 #1032 音乐播放器
  Soft1614080902422/#5Report.md
  Soft1614080902422/1.png
  Soft1614080902422/2.png
  Soft1614080902422/3.png
  Soft1614080902422/java/edu/hzuapps/androidlabs/soft1614080902422/Soft1614080902422Activity_01.java
  Soft1614080902422/res/layout/activity_soft1614080902422_01.xml
Labels: Good

#2036 #2 迟来的第二次实验！！#
  com1614080901115/app/AndroidManifest.xml
  com1614080901115/app/java/Com1614080901115Activity.java
  com1614080901115/app/report2.md
  com1614080901115/app/res/layout/activity_com1614080901115.xml
  com1614080901115/app/res/values/strings.xml
  com1614080901115/app/实验二截图.png
Labels: Late

#2031 #5 #991 第五次实验
  soft1614080902440/Fifth/Soft1614080902440p1.png
  soft1614080902440/Fifth/Soft1614080902440p2.png
  soft1614080902440/Fifth/report5.md
  soft1614080902440/app/src/main/AndroidManifest.xml
  soft1614080902440/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902440/Soft1614080902440Activity2.java
  soft1614080902440/app/src/main/res/layout/activity2_soft1614080902440.xml
Labels: Good

#2053 #2034 实验3
  com1614080901145/app/report3.md
  com1614080901145/app/src/main/AndroidManifest.xml
  com1614080901145/app/src/main/java/com/example/zhang/com1614080901145/Com1614080901145Activity.java
  com1614080901145/app/src/main/java/com/example/zhang/com1614080901145/Com_1614080901145Activity.java
  com1614080901145/app/src/main/res/drawable-v24/bgp.png
  com1614080901145/app/src/main/res/layout/activity_com1614080901145.xml
  com1614080901145/app/src/main/res/layout/activity_com_1614080901145.xml
  com1614080901145/截图1.PNG
  com1614080901145/截图2.PNG
Labels: Late

#2028 #第二次实验
  soft1614080902443/app/src/main/AndroidManifest.xml
  soft1614080902443/app/src/main/java/soft1614080902443/java/edu/hzuapps/androidlabs/soft1614080902443/Soft1614080902443Activity.java
  soft1614080902443/app/src/main/res/layout/activity_soft1614080902443.xml
  soft1614080902443/app/src/main/res/values/strings.xml
  soft1614080902443/report2.md
Labels: Late

#2087 #5 #11 实验5 TIM存储功能
  Soft1614080902145/TIM/src/main/java/com/example/hao/soft1614080902145/Message_Activity.java
  Soft1614080902145/TIM/src/main/res/layout/activity_message_.xml
  Soft1614080902145/report5.md
  Soft1614080902145/sy5-1.png
  Soft1614080902145/sy5-2.png
Labels: Good

#2086 #3 第三次实验
  soft1614080902303/AndroidManifest.xml
  soft1614080902303/Java/Main2Activity.java
  soft1614080902303/Java/MainActivity.java
  soft1614080902303/Main2Activity.PNG
  soft1614080902303/MainActivity.PNG
  soft1614080902303/drawable/ic_launcher_background.xml
  soft1614080902303/drawable/jiaoshi.jpg
  soft1614080902303/drawable/pikaqiu.jpg
  soft1614080902303/layout/activity_main.xml
  soft1614080902303/layout/activity_main2.xml
  soft1614080902303/report3.md
  soft1614080902303/values/strings.xml
Labels: Late

#2072 #5 #1013 第五次实验
  soft1614080902332/002.png
  soft1614080902332/004.png
  soft1614080902332/005.png
  soft1614080902332/006.png
  soft1614080902332/007.png
  soft1614080902332/008.png
  soft1614080902332/app/src/main/AndroidManifest.xml
  soft1614080902332/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902332/Soft1614080902332Activity1.java
  soft1614080902332/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902332/Soft1614080902332Activity2.java
  soft1614080902332/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902332/Soft1614080902332Activity3.java
  soft1614080902332/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902332/Soft1614080902332Activity4.java
  soft1614080902332/app/src/main/res/layout/soft_1614080902332_activity2.xml
  soft1614080902332/app/src/main/res/layout/soft_1614080902332_activity3.xml
  soft1614080902332/report4.md
  soft1614080902332/report5.md
Labels: Good

#2089 #5 #1468 第五次实验
  com1614080901238/app/src/main/java/edu/hzuapps/androidlabs/com1614080901238/Com820238114Activity.java
  com1614080901238/app/src/main/java/edu/hzuapps/androidlabs/com1614080901238/WallpaperItemActivity.java
  com1614080901238/app/src/main/java/edu/hzuapps/androidlabs/com1614080901238/adapter/ItemContentAdapter.java
  com1614080901238/app/src/main/java/edu/hzuapps/androidlabs/com1614080901238/adapter/WallpaperAdapter.java
  com1614080901238/app/src/main/java/edu/hzuapps/androidlabs/com1614080901238/db/WallpaperDB.java
  com1614080901238/app/src/main/java/edu/hzuapps/androidlabs/com1614080901238/entity/ItemContent.java
  com1614080901238/app/src/main/res/layout/com820238114_activity.xml
  com1614080901238/app/src/main/res/layout/comment_item.xml
  com1614080901238/app/src/main/res/layout/rv_item.xml
  com1614080901238/app/src/main/res/layout/wallpaper_item_activity.xml
  com1614080901238/实验五实验报告.md
  com1614080901238/实验五运行截图/1.png
  com1614080901238/实验五运行截图/2.png
  com1614080901238/实验五运行截图/3.png
  com1614080901238/实验五运行截图/4.png
  com1614080901238/实验五运行截图/5.png
Labels: Good

#2130 #2#1599#第二次实验
  soft1614080902141/AndroidManifest.xml
  soft1614080902141/MainActivity.java
  soft1614080902141/activity_main.xml
  soft1614080902141/report2.md
  soft1614080902141/res/layout/activity_main.xml
  soft1614080902141/res/values/strings.xml
  soft1614080902141/strings.xml
Labels: Late

#2137 #3 #921第三次实验
  soft1614080902241/3_1.jpg
  soft1614080902241/3_2.jpg
  soft1614080902241/app/src/main/AndroidManifest.xml
  soft1614080902241/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902241/SecondActivity.java
  soft1614080902241/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902241/Soft1614080902241Activity.java
  soft1614080902241/app/src/main/res/drawable/huanying.png
  soft1614080902241/app/src/main/res/layout/activity_second.xml
  soft1614080902241/app/src/main/res/layout/activity_soft1614080902241.xml
  soft1614080902241/app/src/main/res/values/strings.xml
  soft1614080902241/report3.md
Labels: Late

#2139 #3 第3次实验
  com1614080901104/app/src/main/AndroidManifest.xml
  com1614080901104/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901104/com1614080901104Activity.java
  com1614080901104/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901104/secondActivity.java
  com1614080901104/report3.md
Labels: Late

#2148 “迟来的第三次实验！！”
  com1614080901115/app/AndroidManifest.xml
  com1614080901115/app/java/Button1Activity.java
  com1614080901115/app/java/Button2Activity.java
  com1614080901115/app/java/Button3Activity.java
  com1614080901115/app/java/Button4Activity.java
  com1614080901115/app/java/Com1614080901115Activity.java
  com1614080901115/app/java/SecondActivity.java
  com1614080901115/app/report3.md
  com1614080901115/app/report4.md
  com1614080901115/app/res/drawable/beijing.jpg
  com1614080901115/app/res/drawable/chiji.jpg
  com1614080901115/app/res/drawable/friends.png
  com1614080901115/app/res/drawable/ji1.jpg
  com1614080901115/app/res/drawable/ji2.jpg
  com1614080901115/app/res/drawable/ji3.jpg
  com1614080901115/app/res/drawable/ji4.jpg
  com1614080901115/app/res/drawable/my.png
  com1614080901115/app/res/drawable/news.png
  com1614080901115/app/res/drawable/pk.png
  com1614080901115/app/res/layout/activity_com1614080901115.xml
  com1614080901115/app/res/layout/activity_second.xml
  com1614080901115/app/res/layout/button1.xml
  com1614080901115/app/res/layout/button2.xml
  com1614080901115/app/res/layout/button3.xml
  com1614080901115/app/res/layout/button4.xml
  com1614080901115/app/res/values/strings.xml
  com1614080901115/app/实验三截图.png
  com1614080901115/app/实验三首页截图.png
  com1614080901115/app/实验四截图.png
Labels: Late

#2181 第二次实验
  soft1614080902210/app/src/main/AndroidManifest.xml
  soft1614080902210/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902210/soft1614080902210.java
  soft1614080902210/app/src/main/res/layout/activity_soft1614080902210.xml
  soft1614080902210/app/src/main/res/layout/values/strings.xml
  soft1614080902210/report2.md
  soft1614080902210/捕获.PNG
Labels: Late

#2172 第三、四次实验
  soft1614080902214/a.PNG
  soft1614080902214/b.PNG
  soft1614080902214/c.PNG
  soft1614080902214/d.PNG
  soft1614080902214/lock/app/src/main/AndroidManifest.xml
  soft1614080902214/lock/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902214/SecondActivity.java
  soft1614080902214/lock/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902214/soft1614080902214.java
  soft1614080902214/lock/app/src/main/res/drawable/timg.png
  soft1614080902214/lock/app/src/main/res/layout/activity_second.xml
  soft1614080902214/lock/app/src/main/res/layout/activity_soft1614080902214.xml
  soft1614080902214/lock/app/src/main/res/values/strings.xml
  soft1614080902214/report3.md
  soft1614080902214/report4.md
Labels: Late

#2179 #6 #957 第六次实验
  soft1614080902221/app/src/main/AndroidManifest.xml
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Activity3.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/Activity5.java
  soft1614080902221/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902221/HttpUtil.java
  soft1614080902221/app/src/main/res/layout/activity_3.xml
  soft1614080902221/app/src/main/res/layout/activity_5.xml
  soft1614080902221/report6.md
  soft1614080902221/第六次实验截图.gif
  soft1614080902221/网络排行榜.json
Labels: Good

#2185 #6 #999
  soft1614080902427/Big Big World.mp3
  soft1614080902427/I23KW.png
  soft1614080902427/Soft1614080902427Activity.java
  soft1614080902427/java/edu/hzuapps/androidlabs/soft1614080902427/Downloader.java
  soft1614080902427/java/edu/hzuapps/androidlabs/soft1614080902427/DownloaderListener.java
  soft1614080902427/java/edu/hzuapps/androidlabs/soft1614080902427/Player.java
  soft1614080902427/java/edu/hzuapps/androidlabs/soft1614080902427/Soft1614080902427Activity.java
  soft1614080902427/manifests/AndroidManifest.xml
  soft1614080902427/report6.md
  soft1614080902427/screenshot1.png
  soft1614080902427/screenshot2.png
  soft1614080902427/screenshot3.png
  soft1614080902427/song.json
  soft1614080902427/九龙赞.mp3
  soft1614080902427/勇气.mp3
  soft1614080902427/我欲成仙.mp3
Labels: Good

#2186 #3 第三次实验
  Com1614080901114/app/src/main/AndroidManifest.xml
  Com1614080901114/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901114/Com1614080901114Activity.java
  Com1614080901114/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901114/secondActivity.java
  Com1614080901114/app/src/main/res/drawable/ic_launcher_background.xml
  Com1614080901114/app/src/main/res/drawable/pho1.png
  Com1614080901114/app/src/main/res/drawable/pho2.png
  Com1614080901114/app/src/main/res/layout/activity_com1614080901114.xml
  Com1614080901114/app/src/main/res/layout/activity_second.xml
  Com1614080901114/app/src/main/res/values/strings.xml
  Com1614080901114/jietu1.jpg
  Com1614080901114/jietu2.png
  Com1614080901114/report3.md
Labels: Late

#2191 #2 #1668 第二次实验
  com1614080901102/app/src/main/AndroidManifest.xml
  com1614080901102/app/src/main/java/androidlabs/hzuapps/edu/com1614080901102/Com1614080901102Activity.java
  com1614080901102/app/src/main/res/layout/activity_com1614080901102.xml
  com1614080901102/app/src/main/res/values/strings.xml
  com1614080901102/report1.md
  com1614080901102/report2.md
  com1614080901102/第一次实验报告.md
Labels: Late

#2193 #4 #1647第四次实验及报告
  com1614080901107/4-1.png
  com1614080901107/app/src/main/res/layout/activity_com1614080901107.xml
  com1614080901107/report4.md
Labels: Late

#2184 #3 #887 linkzw 第五次实验报告
  soft1614080902125/app/src/main/AndroidManifest.xml
  soft1614080902125/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902125/RW_file_musiclist.java
  soft1614080902125/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902125/Soft1614080902125Activity.java
  soft1614080902125/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902125/Song.java
  soft1614080902125/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902125/add_music.java
  soft1614080902125/app/src/main/java/edu/hzuapps/androidlabs/soft1614080902125/locallist_Fragment.java
  soft1614080902125/app/src/main/res/drawable/actionbar_more.png
  soft1614080902125/app/src/main/res/drawable/ic_launcher_background.xml
  soft1614080902125/app/src/main/res/drawable/lock_btn_next.png
  soft1614080902125/app/src/main/res/drawable/lock_btn_pause.png
  soft1614080902125/app/src/main/res/drawable/lock_btn_play.png
  soft1614080902125/app/src/main/res/drawable/lock_btn_prev.png
  soft1614080902125/app/src/main/res/layout/main_locallist.xml
  soft1614080902125/app/src/main/res/layout/music_item.xml
  soft1614080902125/app/src/main/res/values/strings.xml
  soft1614080902125/p7.jpg
  soft1614080902125/report5.md
Labels: Late

#2182 #4 第四次实验
  soft1614080902303/Main2Activity.PNG
  soft1614080902303/layout/activity_main.xml
  soft1614080902303/layout/activity_main2.xml
  soft1614080902303/第四次实验报告.md
Labels: Late

#2205 #1 第一次实验
  soft1614080902411/#report.md
  soft1614080902411/Soft1614080902411Activity.png
  soft1614080902411/soft1614080902411Activity.java
Labels: Late

#2202 #2 #2201 from Susie-Lau
  Com1614080901125/#2/#2.png
  Com1614080901125/#2/AndroidManifest.xml
  Com1614080901125/#2/java/MainActivity.java
  Com1614080901125/#2/report2.md
  Com1614080901125/#2/res/layout/activity_main.xml
  Com1614080901125/#2/res/values/strings.xml
Labels: Late

#2203 #5 #994 QQ the 5th lab
  soft1614080902335/java/androidlabs/hzuapps/edu/soft1614080902335/Soft1614080902335Activity3.java
  soft1614080902335/java/androidlabs/hzuapps/edu/soft1614080902335/Soft1614080902335Activity4.java
  soft1614080902335/java/androidlabs/hzuapps/edu/soft1614080902335/UserInformationProvider.java
  soft1614080902335/manifests/AndroidManifest.xml
  soft1614080902335/report5.md
  soft1614080902335/res/layout/activity_soft1614080902335_qq4.xml
  soft1614080902335/res/layout/activity_soft1614080902335_qq5.xml
  soft1614080902335/实验五uml类图.png
  soft1614080902335/实验五截图1.png
  soft1614080902335/实验五截图2.png
Labels: Demo

#2215 #6 #1094 231第六次实验
  soft1614080902231/app/src/main/AndroidManifest.xml
  soft1614080902231/app/src/main/java/com/example/administrator/soft1614080902231/ThreeActivity.java
  soft1614080902231/app/src/main/res/layout/activity_three.xml
  soft1614080902231/informatian.json
  soft1614080902231/r6.png
  soft1614080902231/report6.md
Labels: Good

#2312 #3#1599 实验3
  soft1614080902141/drawable/timg.jpg
  soft1614080902141/java/com/example/john/soft1614080902141/ActivitySecond.java
  soft1614080902141/java/com/example/john/soft1614080902141/MainActivity.java
  soft1614080902141/layout/activity_main.xml
  soft1614080902141/layout/activity_second.xml
  soft1614080902141/report3.md
  soft1614080902141/values/colors.xml
  soft1614080902141/values/dimens.xml
  soft1614080902141/values/strings.xml
  soft1614080902141/values/styles.xml
  soft1614080902141/页面.png
  soft1614080902141/首页.png
Labels: Late

#2332 #3 #1351 第三次实验
  com1614080901130/app/src/main/AndroidManifest.xml
  com1614080901130/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901130/ActivityBasicActivity.java
  com1614080901130/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901130/Anni.java
  com1614080901130/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901130/Com1614080901130Activity.java
  com1614080901130/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901130/Show.java
  com1614080901130/app/src/main/java/edu/hzuapps/androidlabs/Com1614080901130/Upload.java
  com1614080901130/app/src/main/res/drawable/ic_launcher_background.xml
  com1614080901130/app/src/main/res/drawable/share.svg
  com1614080901130/app/src/main/res/layout/activity_activity_basic.xml
  com1614080901130/app/src/main/res/layout/anni_home.xml
  com1614080901130/app/src/main/res/layout/anni_share.xml
  com1614080901130/app/src/main/res/layout/anni_show.xml
  com1614080901130/app/src/main/res/layout/com_1614080901130_activity.xml
  com1614080901130/app/src/main/res/values/colors.xml
  com1614080901130/app/src/main/res/values/strings.xml
  com1614080901130/app/src/main/res/values/styles.xml
  com1614080901130/report/report1.md
  com1614080901130/report/report2.md
  com1614080901130/report/report3.md
  com1614080901130/screen/report3_screen01.png
  com1614080901130/screen/report3_screen02.png
Labels: Late

#2298 第六次实验校开会 app
  soft1614080902425/app/src/main/AndroidManifest.xml
  soft1614080902425/app/src/main/java/com/example/administrator/soft1614080902425/CreatetableActivity.java
  soft1614080902425/app/src/main/java/com/example/administrator/soft1614080902425/Icon.java
  soft1614080902425/app/src/main/java/com/example/administrator/soft1614080902425/ReAdapter.java
  soft1614080902425/app/src/main/java/com/example/administrator/soft1614080902425/Soft1614080902425Activity6.java
  soft1614080902425/app/src/main/java/com/example/administrator/soft1614080902425/nexttableActivity.java
  soft1614080902425/app/src/main/res/drawable/baiduc.png
  soft1614080902425/app/src/main/res/drawable/havaclass1.png
  soft1614080902425/app/src/main/res/drawable/havaclass2.png
  soft1614080902425/app/src/main/res/drawable/havaclass3.png
  soft1614080902425/app/src/main/res/drawable/withoutclass.png
  soft1614080902425/app/src/main/res/layout/activity_createtable.xml
  soft1614080902425/app/src/main/res/layout/activity_nexttable.xml
  soft1614080902425/app/src/main/res/layout/activity_soft1614080902425.xml
  soft1614080902425/app/src/main/res/layout/clas.xml
  soft1614080902425/app/src/main/res/values/colors.xml
  soft1614080902425/实验6截图1.png
  soft1614080902425/实验6截图2.png
  soft1614080902425/实验报告6.md
Labels: Demo

#2432 第一次实验(截图版)
  soft1614080902127/report1.md
  soft1614080902127/实验1截图.png
Labels: Late

#2388 #3 第3次实验
  soft1614080902106/app/src/main/java/com/example/asus/soft1614080902106/Soft1614080902106Main2Activity.java
  soft1614080902106/app/src/main/java/com/example/asus/soft1614080902106/Soft1614080902106MainActivity.java
  soft1614080902106/app/src/main/res/drawable/ic_launcher_background.xml
  soft1614080902106/app/src/main/res/drawable/timg.jpg
  soft1614080902106/app/src/main/res/layout/activity_soft1614080902106_main.xml
  soft1614080902106/app/src/main/res/layout/activity_soft1614080902106_main2.xml
  soft1614080902106/app/src/main/res/layout/activity_soft1614080902106_main3.xml
  soft1614080902106/report3.md
  soft1614080902106/shiyansan-1.jpg
  soft1614080902106/shiyansan.png
Labels: Late

#2433 #3 第三次实验截图及报告
  Soft1614080902136/app/src/main/AndroidManifest.xml
  Soft1614080902136/app/src/main/java/com/example/soft1614080902136/Soft1614080902136Activity.java
  Soft1614080902136/app/src/main/java/com/example/soft1614080902136/Soft1614080902136Activity2.java
  Soft1614080902136/app/src/main/res/drawable/timg.jpg
  Soft1614080902136/app/src/main/res/layout/activity_soft1614080902136.xml
  Soft1614080902136/app/src/main/res/layout/activity_soft16140809021362.xml
  Soft1614080902136/app/src/main/res/values/strings.xml
  Soft1614080902136/report3.md
  Soft1614080902136/第三次实验截图1.png
  Soft1614080902136/第三次实验截图2.png
Labels: Late

#2454 实验3
  soft1614080902127/app/src/main/AndroidManifest.xml
  soft1614080902127/app/src/main/java/hdu/hzuapps/androidlabs/soft1614080902127/SecondActivity.java
  soft1614080902127/app/src/main/java/hdu/hzuapps/androidlabs/soft1614080902127/Soft1614080902127Activity.java
  soft1614080902127/app/src/main/res/drawable/timg.jpg
  soft1614080902127/app/src/main/res/layout/activity_second.xml
  soft1614080902127/app/src/main/res/layout/activity_soft1614080902127.xml
  soft1614080902127/report3.md
  soft1614080902127/实验3-1.png
  soft1614080902127/实验3-2.png
Labels: Late

#2345 实验3
  soft1614080902134/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902134/WangZheActivity.java
  soft1614080902134/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902134/WangZheLogActivity.java
  soft1614080902134/app/src/main/res/drawable/kaishi.png
  soft1614080902134/app/src/main/res/drawable/right.png
  soft1614080902134/app/src/main/res/drawable/view.png
  soft1614080902134/app/src/main/res/drawable/wangzhe.png
  soft1614080902134/app/src/main/res/drawable/wrong.png
  soft1614080902134/app/src/main/res/layout/activity_wang_zhe.xml
  soft1614080902134/app/src/main/res/layout/activity_wang_zhe_log.xml
  soft1614080902134/report1.md
  soft1614080902134/report3.md
  soft1614080902134/report4.md
  soft1614080902134/reprot2.md
  soft1614080902134/reprot2.rm
  soft1614080902134/shiyansan1.png
  soft1614080902134/shiyansan2.png
  soft1614080902134/实验四.png
  soft1614080902134/实验四1.png
Labels: Late

#2500 #4 #902 第4次实验
  soft1614080902106/app/src/main/AndroidManifest.xml
  soft1614080902106/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902106/Soft1614080902106Activity.java
  soft1614080902106/app/src/main/java/edu/hzuapps/androidlabs/Soft1614080902106/soft1614080902106.java
  soft1614080902106/app/src/main/res/drawable/1.png
  soft1614080902106/app/src/main/res/drawable/2.png
  soft1614080902106/app/src/main/res/layout/activity2_soft1614080902106.xml
  soft1614080902106/app/src/main/res/layout/activity_soft1614080902106.xml
  soft1614080902106/实验3/src/main/AndroidManifest.xml
  soft1614080902106/实验3/src/main/java/com/example/asus/soft1614080902106/Soft1614080902106Main2Activity.java
  soft1614080902106/实验3/src/main/java/com/example/asus/soft1614080902106/Soft1614080902106MainActivity.java
  soft1614080902106/实验3/src/main/java/edu/hzuapps/androidlabs/Soft1614080902106/Soft1614080902106Activity.java
  soft1614080902106/实验3/src/main/java/edu/hzuapps/androidlabs/Soft1614080902106/soft1614080902106.java
  soft1614080902106/实验3/src/main/res/drawable/1.png
  soft1614080902106/实验3/src/main/res/drawable/2.png
  soft1614080902106/实验3/src/main/res/drawable/ic_launcher_background.xml
  soft1614080902106/实验3/src/main/res/drawable/timg.jpg
  soft1614080902106/实验3/src/main/res/layout/activity2_soft1614080902106.xml
  soft1614080902106/实验3/src/main/res/layout/activity_soft1614080902106.xml
  soft1614080902106/实验3/src/main/res/layout/activity_soft1614080902106_main.xml
  soft1614080902106/实验3/src/main/res/layout/activity_soft1614080902106_main2.xml
  soft1614080902106/实验3/src/main/res/layout/activity_soft1614080902106_main3.xml
Labels: Late

#2516 第二次实验修改
  soft1614080902107/AndroidManifest.xml
  soft1614080902107/Soft1614080902107MainActivity.java
  soft1614080902107/activity_soft1614080902107_main.xml
  soft1614080902107/report2.md
  soft1614080902107/strings.xml
Labels: Late

#2346 #4 #987 第四次实验及运行结果
  Soft1613071002205/app1/src/main/AndroidManifest.xml
  Soft1613071002205/app1/src/main/res/drawable/homepage.jpg
  Soft1613071002205/app1/src/main/res/drawable/ic_launcher_background.xml
  Soft1613071002205/app1/src/main/res/drawable/个人界面.jpg
  Soft1613071002205/app1/src/main/res/layout/activity_main.xml
  Soft1613071002205/app1/src/main/res/layout/home.xml
  Soft1613071002205/app1/src/main/res/layout/mynews.xml
  Soft1613071002205/app1/src/main/res/values/colors.xml
  Soft1613071002205/app1/src/main/res/values/strings.xml
  Soft1613071002205/app1/src/main/res/values/styles.xml
  Soft1613071002205/app1/运行截图/个人界面.png
  Soft1613071002205/app1/运行截图/信息发布.png
  Soft1613071002205/app1/运行截图/首页.jpg
Labels: Late

#2430 #4 #1381 第四次实验
  com1614080901104/app/src/main/res/drawable-v24/background.jpg
  com1614080901104/app/src/main/res/layout/activity_second.xml
  com1614080901104/report4.md
  com1614080901104/第四次实验截图.png
Labels: Late

#2492 #4实验四（之前实验三很早做好，一直忘了上传，抱歉）
  com1614080901135/app/src/main/AndroidManifest.xml
  com1614080901135/app/src/main/java/com/example/hzu/com1614080901135/com1614080901135Activity.java
  com1614080901135/app/src/main/java/com/example/hzu/com1614080901135/secondActivity.java
  com1614080901135/app/src/main/res/drawable/t.jpg
  com1614080901135/app/src/main/res/layout/activity_com1614080901135.xml
  com1614080901135/app/src/main/res/layout/activity_second.xml
  com1614080901135/app/src/main/res/values/strings.xml
  com1614080901135/report3.md
  com1614080901135/tt4-1.png
  com1614080901135/第一个界面.png
  com1614080901135/第二个界面.png
Labels: Late

#2486 #第四次实验 纸牌
  soft1606070302104/AndroidManifest.xml
  soft1606070302104/app/src/main/java/edu/hzuapps/androidlabs2018/soft1606070302104/Soft1606070302104Activity.java
  soft1606070302104/app/src/main/java/edu/hzuapps/androidlabs2018/soft1606070302104/third3Activity.java
  soft1606070302104/app/src/main/res/drawable/m.png
  soft1606070302104/app/src/main/res/drawable/s.png
  soft1606070302104/app/src/main/res/layout/activity_second2.xml
  soft1606070302104/app/src/main/res/layout/activity_soft1606070302104.xml
  soft1606070302104/app/src/main/res/layout/activity_third3.xml
  soft1606070302104/report 4.md
  soft1606070302104/test4-1.png
  soft1606070302104/test4-2.png
  soft1606070302104/test4-3.png
Labels: Late

#2485 #4 第四次实验加报告
  com1614080901230/3.png
  com1614080901230/4.png
  com1614080901230/app1/src/main/AndroidManifest.xml
  com1614080901230/app1/src/main/java/edu/hzuapps/androidlabs/com1614080901230/SecondActivity.java
  com1614080901230/app1/src/main/java/edu/hzuapps/androidlabs/com1614080901230/com1614080901230Activity.java
  com1614080901230/app1/src/main/res/layout/activity_com1614080901230.xml
  com1614080901230/app1/src/main/res/layout/activity_second.xml
  com1614080901230/app1/src/main/res/layout/content_second.xml
  com1614080901230/report4.md
Labels: Late

#2520 #3 #4 #933 第3、4次实验作业
  soft1614080902109/app/src/main/AndroidManifest.xml
  soft1614080902109/app/src/main/java/soft1614080902109/soft1614080902109/FragmentTabLocal.java
  soft1614080902109/app/src/main/java/soft1614080902109/soft1614080902109/MainActivity.java
  soft1614080902109/app/src/main/java/soft1614080902109/soft1614080902109/MyFragment.java
  soft1614080902109/app/src/main/java/soft1614080902109/soft1614080902109/NewFileActivity.java
  soft1614080902109/app/src/main/res/drawable/ic_launcher_background.xml
  soft1614080902109/app/src/main/res/drawable/ic_newfile.png
  soft1614080902109/app/src/main/res/drawable/ic_upload.png
  soft1614080902109/app/src/main/res/drawable/my_schedule.png
  soft1614080902109/app/src/main/res/drawable/ss.xml
  soft1614080902109/app/src/main/res/drawable/tab_menu_color.xml
  soft1614080902109/app/src/main/res/drawable/tab_menu_find.xml
  soft1614080902109/app/src/main/res/drawable/tab_menu_local.xml
  soft1614080902109/app/src/main/res/drawable/tab_menu_user.xml
  soft1614080902109/app/src/main/res/layout/activity_main.xml
  soft1614080902109/app/src/main/res/layout/fg_content.xml
  soft1614080902109/app/src/main/res/layout/tab_fg_1.xml
  soft1614080902109/app/src/main/res/layout/tab_fg_2.xml
  soft1614080902109/app/src/main/res/layout/tab_fg_3.xml
  soft1614080902109/app/src/main/res/values/colors.xml
  soft1614080902109/app/src/main/res/values/strings.xml
  soft1614080902109/app/src/main/res/values/styles.xml
  soft1614080902109/report3.md
  soft1614080902109/report4.md
  soft1614080902109/第三次实验图片1.png
  soft1614080902109/第三次实验图片2.png
  soft1614080902109/第四次实验截图.png
  soft1614080902109/第四次实验截图2.png
Labels: Late

#2519 实验三
  Soft1614080902301/app/src/main/AndroidManifest.xml
  Soft1614080902301/app/src/main/java/edu/androidlabs/hzuapps/tk/Main2Activity.java
  Soft1614080902301/app/src/main/java/edu/androidlabs/hzuapps/tk/MainActivity.java
  Soft1614080902301/app/src/main/res/drawable/ic_launcher_background.xml
  Soft1614080902301/app/src/main/res/drawable/tuku.jpg
  Soft1614080902301/app/src/main/res/layout/activity_main.xml
  Soft1614080902301/app/src/main/res/layout/activity_main2.xml
  Soft1614080902301/app/src/main/res/values/strings.xml
  Soft1614080902301/实验三.jpg
  Soft1614080902301/实验三.md
Labels: Late
