Repository hzuapps/android-labs-2018, pull requests merged in 2018-03, with the labels that each got.

#23 #1 实验1
  com1614080901113/Com1614080901113Activity.java
Labels: Good

#57 #1 第1次实验
  soft1614080902121/Soft1614080902121Activity.java
Labels: Good

#58 #1 第1次实验 for com
  com1614080901141/Com1614080901141Activity.java
Labels: Good

#63 #1 第1次实验
  soft1614080902427/Soft1614080902427Activity.java
Labels: Good

#65 #1 #123 第1次实验
  soft1614080902403/Soft164080902403Activity.java
Labels: Good

#66 #1 第一次实验
  soft1614080902307/Soft1614080902307Activity.java
Labels: Good

#67 #1 first labs
  soft1614080902409/Soft1614080902409Activitly.java
Labels: Good

#68 #1 第一次实验
  soft1613071002123/Soft1613071002123Activity1.java
  soft1613071002123/Soft1613071002123Activity2.java
  soft1613071002123/Soft1613071002123Activity3.java
Labels: Good

#69 #1 第一次实验
  Soft1614080902444/Soft1614080902444Activity.java
Labels: Good

#71 #1 第一次实验 for soft
  soft1614080902443/Soft1614080902443Activity.java
Labels: Good

#75 #1 first lab demo
  soft1614080902329/soft1614080902329Activity.java
  soft1614080902329/soft1614080902329Activity2.java
Labels: Good

#76 #1 soft1614080902320 第一次实验
  soft1614080902320/Soft1614080902320Activity.java
Labels: Good

#77 #1 第一次实验 for soft
  soft1614080902437/Soft1614080902437Activity.java
Labels: Good

#79 #1 first demo
  soft1614080902341/Soft1614090902341Activity3.java
Labels: Good

#81 #1 first lab demo
  soft1614080902325/Soft1614080902325Activity.java
Labels: Good

#82 #1 第一次实验
  soft1614080902442/Soft1614080902442Activity.java
Labels: Good

#86 #1 first 第一次实验
  soft1614080902313/Soft1614080902313Activity.java
Labels: Good

#91 #1 第一次实验
  soft1614080902328/Soft1614080902328Activity.java
Labels: Good

#92 #1 the first lab
  soft1614080902335/Soft1614080902335Activity.java
Labels: Good

#95 #1 first
  soft1614080902338/Soft1614080902338Activity.java
Labels: Good

#96 #1 #17 frist lab
  soft1614080902417/Soft1614080902417.java
Labels: Good

#97 #1#zhongtf 第一次实验
  soft1614080902322/Soft1614080902322Activity.java
Labels: Good

#98 #1 第一次实验
  soft1614080902412/Soft1614080902412Activity.java
Labels: Good

#105 #1 第一次实验
  soft1614080902424/Soft1614080902424Activity.java
Labels: Good

#108 #1 Zhuangyupeng第一次实验
  soft1614080902430/Soft1614080902430Activity.java
Labels: Good

#110 #1 第1次实验
  soft1614080902132/Soft1614080902132Activity.java
Labels: Good

#116 #1 第1次实验
  soft1614080902114/Soft1614080902114Activity.java
Labels: Good

#129 #1第一次实验
  soft1614080902414/Soft1614080902414Activity.java
Labels: Good

#130 #1 第1次实验
  soft1614080902316/Soft1614080902316Activity.java
Labels: Good

#133 #1 第一次实验 for hy
  com1614080901207/Com1614080901207Activity.java
Labels: Good

#141 #1 super zenglinsheng第一次实验
  soft1614080902445/Soft1614080902445Activity.java
Labels: Good

#136 #1 第1次实验
  soft1614080902109/Soft1614080902109Activity.java
Labels: Good

#135 #1 第一次实验
  soft1614080902319/Soft1614080902319Activity.java
Labels: Good

#134 #1 first lab
  soft1614080902334/Soft1614080902334Activity.java
Labels: Good

#150 #1 myfirst demo
  soft1609081602618/Soft1609081602618Activity.java
Labels: Good

#151 #1 第一次实验
  soft1614080902440/Soft1614080902440Activity.java
Labels: Good

#154 #1 第一次实验
  soft1614080902342/Soft1614080902342Activicy.java
Labels: Good

#158 #1 第一次实验
  soft1614080902402/Soft1614080902402Activity.java
Labels: Good

#159 #1Rvelamen第一次实验
  soft1614080902130/Soft1614080902130Activity.java
Labels: Good

#164 #1 第一次实验
  com1614080901140/Com1614080901140Activity.java
Labels: Good

#166 #1 first demo from Strakly
  soft1614080902339/Soft1614080902339Activity.java
Labels: Good

#168 #1 #ByaoHe 第一次实验
  soft1614080902303/Soft1614080902303Activity.java
Labels: Good

#162 #1 first demo from LaineChen
  com1614080901225/Com1614080901225Activity.java
Labels: Good

#176 #1 第一次实验
  com1614080901126/Com1614080901126Activity.java
Labels: Good

#173 #1 first lab demo
  soft1614080902332/Soft1614080902332Activity.java
Labels: Good

#186 #1 #szayd 第一次实验
  com1614080901133/Com1614080901133Activity.java
Labels: Good

#193 #1 #216 第一次实验
  soft1614080902216/Soft1614080902216Activity.java
Labels: Good

#194 #1
  com1613090502214/Com1613090502214Activity.java
Labels: Good

#196 #1 #1614080902436 first
  soft1614080902436/Soft1614080902436Activity.java
Labels: Good

#188 #1 #JianPengChen 第一次实验
  Com1614080901111/Com1614080901111Activity.java
Labels: Good

#201 #1 第一次实验
  Soft1614080902333/Soft161080902333Activity2.java
Labels: Good

#203 #1 first lab
  Soft1614080902312/Soft1614080902312Activity.java
Labels: Good

#206 #1 first lab demo
  soft1614080902413/Soft1614080902413Activity.java
Labels: Example, Good

#208 #1 first lab
  soft1614080902309/Soft1614080902309Activity2.java
Labels: Example, Good

#209 #1 DcXuhm 第一次试验
  soft1614080902337/Soft1614080902337Activity.java
Labels: Good

#476 #1 第1次实验
  Soft1614080902116/Soft1614080902116Activity.java
Labels: Demo

#435 #1#1第一次实验
  soft1606070302104/Soft1606070302104Activity.java
Labels: Demo
